# Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import KFold, train_test_split, GroupKFold
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score, f1_score, precision_recall_fscore_support
from tensorflow.keras.models import Model, Sequential, load_model
from tensorflow.keras.layers import Input, Conv1D, Conv2D, MaxPooling1D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization, LSTM, SimpleRNN, GRU, ConvLSTM2D, Bidirectional, TimeDistributed, GaussianNoise, concatenate
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import plot_model, to_categorical
from torch.utils.data import DataLoader, TensorDataset
import os
import sys
import time
import csv

"    \n    'F1': ['d1', 'd3', '12-x', '12-y', '16-x', '16-y', '14-x', '14-y', 'Raw-accel-x', 'Raw-accel-y', 'Raw-accel-z'],\n    'F2': ['d1', 'd3', 'd5', 'd7', '16-x', '16-y', '14-x', '14-y', 'Raw-accel-x', 'Raw-accel-y', 'Raw-accel-z'],   \n    'F3': ['d1', 'd3', '12-x', '12-y', '16-x', '16-y', '14-x', '14-y', 'd5', 'd7', 'Raw-accel-x', 'Raw-accel-y', 'Raw-accel-z'],\n    'F4': ['d1', 'd3', '12-x', '12-y', '16-x', '16-y', '14-x', '14-y', '11-x', '11-y', 'Raw-accel-x', 'Raw-accel-y', 'Raw-accel-z'],\n    'F5': ['11-x', '11-y', '12-x', '12-y', '13-x', '13-y', '14-x', '14-y', '15-x', '15-y', '16-x', '16-y', '0-x', '0-y', 'd1', 'd2', 'd3', 'd4', 'd5', 'd6', 'd7', 'd8', 'Raw-accel-x', 'Raw-accel-y', 'Raw-accel-z']\n\n  "

# DataToImage

In [ ]:

def read_data(file_name):
    
    df = pd.read_csv(file_name, sep='\t')
    return df


# Sliding windows on the timestamps 

def rolling_window(fileName, window_size,freq): # window size is specified by user, freq means the overlap
    array = np.array(fileName.astype(float))
    #array = float(np.nan_to_num(array)) #put 0 in nan place
    shape = (array.shape[0] - window_size + 1, window_size)
    strides = (array.strides[0],) + array.strides
    rolled = np.lib.stride_tricks.as_strided(array, shape=shape, strides=strides)
    return rolled[np.arange(0,shape[0],freq)]



def siplite_scaleFiles(dataframe, window, stride, columns):
    scaler = MinMaxScaler(feature_range=(0, 255))
    results = {}

    # Iterate over the columns and assign each to a letter starting from 'a'
    for idx, column in enumerate(columns):
        letter = chr(ord('a') + idx)  # Generate letters 'a', 'b', 'c', etc.
        scaled_data = scaler.fit_transform(rolling_window(dataframe[column].values, window, stride))
        results[letter] = scaled_data  # Store the result in a dictionary with the letter as key

    # Return the values of the dictionary in the order of the letters
    return tuple(results[chr(ord('a') + i)] for i in range(len(columns)))

def feature_sets(scaled_values,bundle):

    if bundle == "F0" or bundle == "F1" or bundle == "F2":
        # Assign variables dynamically using unpacking
        a, b, c, d, e, f, g, h, i, j, k = scaled_values

        # Vision feature stacking (using the order specified)
        vision = np.hstack((a, b, c, d, e, f, g, h, a, c, e, g, a, d, f, h, b, d, g, b, e, h, c, f, a, e))

        # IMU feature stacking
        imu = np.hstack((i, j, k, i, j, k, i, j, k, i, j, k, i))
        
        nvision = 26

        nimu = 13
    elif bundle == "F3" or bundle == "F4":
        # Assign variables dynamically using unpacking
        a, b, c, d, e, f, g, h, i, j,s,p,n = scaled_values
        print(f"Executing block for {bundle}")
        # Vision feature stacking (using the order specified)
        vision = np.hstack((a,b,c,d,e,f,g,h,i,j,a,c,e,g,i,a,d,f,h,j,b,d,g,j,c,f,i,b,e,h,a,e,i,c,g,a,f,j,d,h,b,f))

        # IMU feature stacking
        imu = np.hstack((s,p,n,s,p,n,s,p,n,s,p,n,s))
        
        nvision = 42

        nimu = 13

    elif bundle == "F5":
        # Assign variables dynamically using unpacking
        a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y = scaled_values

        # Vision feature stacking (using the order specified)
        vision = np.hstack((a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,a,c,e,g,i,k,m,o,q,s,u,a,d,f,h,j,l,n,p,r,t,v,b,d,g,j,m,p,s,v,c,f,i,l,o,r,u,b,e,h,k,n,q,t,a,e,i,m,q,u,c,g,k,o,s,a,f,j,n,r,v,d,h,l,p,t,b,f,k,p,u,d,i,n,s,b,g,l,q,v,e,j,o,t,c,h,m,r,a,g,m,s,c,i,o,u,e,k,q,a,h,n,t,d,j,p,v,f,l,r,b,h,o,v,g,n,u,f,m,t,e,l,s,d,k,r,c,j,q,b,i,p,a,i,q,c,k,s,e,m,u,g,o,a,j,r,d,l,t,f,n,v,h,p,b,j,s,f,o,b,k,t,g,p,c,l,u,h,q,d,m,v,i,r,e,n,a,k,u,i,s,g,q,e,o,c,m,a,l,v,j,t,h,r,f,p,d,n,b,l))

        # IMU feature stacking
        imu = np.hstack((w,x,y,w,x,y,w,x,y,w,x,y,w)) 
        
        nvision = 222

        nimu = 13
    return vision, imu , nvision, nimu

def stack_Data(dataframe, window, stride, columns,bundle):
    subject_column = dataframe['subject'].values
    unique_subjects = np.unique(subject_column)
    
    all_stacked1 = []
    all_stacked2 = []
    all_subjects = []
    
    for sub in unique_subjects:
        sub_dataframe = dataframe[dataframe['subject'] == sub]

        # Dynamically assign the letters from siplite_scaleFiles output
        scaled_values = siplite_scaleFiles(sub_dataframe, window, stride, columns)
        
        # Get vision and imu feature sets
        vision, imu , nvision, nimu = feature_sets(scaled_values,bundle)

        # Stack sensor data channels
        h1 = vision
        i1 = imu

        h1 = h1.reshape((h1.shape[0], nvision, window)) # convert sensor data to image  26
        i1 = i1.reshape((i1.shape[0], nimu, window)) # 13

        all_stacked1.append(h1)
        all_stacked2.append(i1) 

        # Append the subject 'sub' for each row in h1
        all_subjects.append(np.full((h1.shape[0], 1), sub)) 
         


    return np.vstack(all_stacked1), np.vstack(all_stacked2), np.vstack(all_subjects)


def DataToImage(WindowSize,Overlapping,columns,bundle):

    ex11_v , ex11_i , subject11 = stack_Data(read_data('data/11.txt'), WindowSize, Overlapping ,columns,bundle)
    ex12_v , ex12_i , subject12= stack_Data(read_data('data/12.txt'), WindowSize, Overlapping ,columns,bundle)
    ex13_v , ex13_i , subject13= stack_Data(read_data('data/13.txt'), WindowSize, Overlapping ,columns,bundle)
    ex21_v , ex21_i , subject21= stack_Data(read_data('data/21.txt'), WindowSize, Overlapping ,columns,bundle)
    ex22_v , ex22_i , subject22= stack_Data(read_data('data/22.txt'), WindowSize, Overlapping ,columns,bundle)
    ex23_v , ex23_i , subject23= stack_Data(read_data('data/23.txt'), WindowSize, Overlapping ,columns,bundle)
    ex31_v , ex31_i , subject31= stack_Data(read_data('data/31.txt'), WindowSize,Overlapping ,columns,bundle)
    ex32_v , ex32_i , subject32= stack_Data(read_data('data/32.txt'), WindowSize, Overlapping ,columns,bundle)
    ex33_v , ex33_i , subject33= stack_Data(read_data('data/33.txt'), WindowSize, Overlapping ,columns,bundle)
    ex41_v , ex41_i , subject41= stack_Data(read_data('data/41.txt'), WindowSize, Overlapping ,columns,bundle)
    ex42_v , ex42_i , subject42= stack_Data(read_data('data/42.txt'), WindowSize, Overlapping ,columns,bundle)
    ex43_v , ex43_i , subject43= stack_Data(read_data('data/43.txt'), WindowSize, Overlapping ,columns,bundle)
    #stack all images datasets in one set
    data_v = np.concatenate((ex11_v,ex12_v,ex13_v,ex21_v,ex22_v,ex23_v,ex31_v,ex32_v,ex33_v,ex41_v,ex42_v,ex43_v), axis=0)
    data_i = np.concatenate((ex11_i,ex12_i,ex13_i,ex21_i,ex22_i,ex23_i,ex31_i,ex32_i,ex33_i,ex41_i,ex42_i,ex43_i), axis=0)
    subject_all = np.concatenate((subject11,subject12,subject13,subject21,subject22,subject23,subject31,subject32,subject33,subject41,subject42,subject43), axis=0)
    
    print(subject_all.shape)
    print(data_i.shape)
    #generate labels for the target images
    y1 = np.zeros([ex11_v.shape[0]], dtype = np.uint8)
    y2 = np.zeros([ex12_v.shape[0]], dtype = np.uint8)
    y3 = np.zeros([ex13_v.shape[0]], dtype = np.uint8)
    y4 = np.zeros([ex21_v.shape[0]], dtype = np.uint8)
    y5 = np.zeros([ex22_v.shape[0]], dtype = np.uint8)
    y6 = np.zeros([ex23_v.shape[0]], dtype = np.uint8)
    y7 = np.zeros([ex31_v.shape[0]], dtype = np.uint8)
    y8 = np.zeros([ex32_v.shape[0]], dtype = np.uint8)
    y9 = np.zeros([ex33_v.shape[0]], dtype = np.uint8)
    y10= np.zeros([ex41_v.shape[0]], dtype = np.uint8)
    y11= np.zeros([ex42_v.shape[0]], dtype = np.uint8)
    y12= np.zeros([ex43_v.shape[0]], dtype = np.uint8)
    y1[:] = 1
    y2[:] = 1
    y3[:] = 1
    y4[:] = 2
    y5[:] = 2
    y6[:] = 2
    y7[:] = 3
    y8[:] = 3
    y9[:] = 3
    y10[:] = 4
    y11[:] = 4
    y12[:] = 4
    #target = np.vstack((y1,y2,y3,y4,y5,y6))
    target = np.concatenate((y1,y2,y3,y4,y5,y6,y7,y8,y9,y10,y11,y12), axis=0)
    #target = np.concatenate((y1,y2,y3,y4,y5), axis=0)
    
    # encode class values as integers
    encoder = LabelEncoder()
    encoder.fit(target)
    encoded_Y = encoder.transform(target)   
    #convert integers to dummy variables (one hot encoded)
    
    Y = np_utils.to_categorical(encoded_Y)
    return data_v, target, Y ,data_i , subject_all


# List of bundles and corresponding column sets
bundle_column_mapping = {

    'F0': ['d1', 'd3', 'd5', 'd7', 'd2', 'd4', 'd6', 'd8', 'Raw-accel-x', 'Raw-accel-y', 'Raw-accel-z'],
    'F1': ['d1', 'd3', '12-x', '12-y', '16-x', '16-y', '14-x', '14-y', 'Raw-accel-x', 'Raw-accel-y', 'Raw-accel-z'],
    'F2': ['d1', 'd3', 'd5', 'd7', '16-x', '16-y', '14-x', '14-y', 'Raw-accel-x', 'Raw-accel-y', 'Raw-accel-z'],   
    'F3': ['d1', 'd3', '12-x', '12-y', '16-x', '16-y', '14-x', '14-y', 'd5', 'd7', 'Raw-accel-x', 'Raw-accel-y', 'Raw-accel-z'],
    'F4': ['d1', 'd3', '12-x', '12-y', '16-x', '16-y', '14-x', '14-y', '11-x', '11-y', 'Raw-accel-x', 'Raw-accel-y', 'Raw-accel-z'],
    'F5': ['11-x', '11-y', '12-x', '12-y', '13-x', '13-y', '14-x', '14-y', '15-x', '15-y', '16-x', '16-y', '0-x', '0-y', 'd1', 'd2', 'd3', 'd4', 'd5', 'd6', 'd7', 'd8', 'Raw-accel-x', 'Raw-accel-y', 'Raw-accel-z']


}

WindowSize = 60      
Overlapping = 15     # Adjust this based on your requirements



# Computed Features

In [ ]:


# Function to read individual data file and assign class labels
def read_data1(file_name, file_class_map):
    print(f"Loading data from {file_name}")
    df1 = pd.read_csv(file_name, sep='\t')
    base_name = file_name.split('/')[-1].split('.')[0]
    df1['class'] = file_class_map[base_name]
    return df1


# Function to load data from a directory and apply class mapping
def load_data1(directory, files, file_class_map):
    data_frames1 = []
    for file_name in files:
        file_path = f'{directory}/{file_name}.txt'
        df1 = read_data1(file_path, file_class_map)
        data_frames1.append(df1)
    return pd.concat(data_frames1, ignore_index=True)


# Function to extract features using a sliding window approach
def extract_features_and_labels(data1, feature_names, window_size, overlap):
    feature_data = data1[feature_names]
    subjects = data1['subject'].values
    labels = data1['class'].values


    n_samples = feature_data.shape[0]
    step = window_size - overlap
    extracted_features = []
    extracted_labels = []
    extracted_subjects = []  # Store subjects for group k-fold


    for start in range(0, n_samples - window_size + 1, step):
        end = start + window_size
        if len(np.unique(subjects[start:end])) == 1:
            window = feature_data.iloc[start:end].values
            mean = np.mean(window, axis=0)
            std = np.std(window, axis=0)
            min_val = np.min(window, axis=0)
            max_val = np.max(window, axis=0)
            extracted_features.append(np.concatenate([mean, std, min_val, max_val]))
            extracted_labels.append(labels[start])
            extracted_subjects.append(subjects[start])


    return np.array(extracted_features), np.array(extracted_labels), np.array(extracted_subjects)



# File names and directories
file_names = ['11', '12', '13', '21', '22', '23', '31', '32', '33', '41', '42', '43']
data_directory = 'data'


# Class mapping
file_class_map = {
    '11': 1, '12': 1, '13': 1,
    '21': 2, '22': 2, '23': 2,
    '31': 3, '32': 3, '33': 3,
    '41': 4, '42': 4, '43': 4
}


all_data = load_data1(data_directory, file_names, file_class_map)




Loading data from data/11.txt
Loading data from data/12.txt
Loading data from data/13.txt
Loading data from data/21.txt
Loading data from data/22.txt
Loading data from data/23.txt
Loading data from data/31.txt
Loading data from data/32.txt
Loading data from data/33.txt
Loading data from data/41.txt
Loading data from data/42.txt
Loading data from data/43.txt


# CNN+CF

In [ ]:
name = "subclass-featurefusion-newfeatures-4class-noise"


# Check if GPU is available and set device accordingly
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')


class CNNWithRF(nn.Module):
    def __init__(self, input_shape_v, input_shape_i, num_classes, num_rf_features):
        super(CNNWithRF, self).__init__()

        # CNN for vision data
        self.cnn_v = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=3),
            nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(32, 64, kernel_size=3),
            nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Flatten()
        )

        # CNN for IMU data
        self.cnn_i = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=3),
            nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(32, 64, kernel_size=3),
            nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Flatten()
        )

        # Calculate CNN output size dynamically
        conv_out_v = self._conv_output_size(input_shape_v)
        conv_out_i = self._conv_output_size(input_shape_i)

        # Dense layers after concatenation
        self.fc = nn.Sequential(
            nn.Linear(conv_out_v + conv_out_i + num_rf_features, 128),
            nn.ReLU(),
            nn.Linear(128, num_classes)
        )

    def _conv_output_size(self, input_shape):
        dummy_input = torch.zeros(1, *input_shape)  
        output = self.cnn_v(dummy_input)
        return int(np.prod(output.size()))

    def forward(self, x_v, x_i, rf_features):
        out_v = self.cnn_v(x_v)
        out_i = self.cnn_i(x_i)
        combined = torch.cat((out_v, out_i, rf_features), dim=1)
        output = self.fc(combined)
        return output


# Train the model for a single fold
def train_model(model, optimizer, criterion, dataloader_train, dataloader_val, epochs=30, fold=None, bundle=None):
    results = {"train_loss": [], "train_accuracy": [], "val_loss": [], "val_accuracy": []}

    for epoch in range(epochs):
        model.train()
        running_loss = 0.0
        correct_train = 0
        total_train = 0

        for X_v, X_i, features, y in dataloader_train:
            # Move data to the GPU
            X_v, X_i, features, y = X_v.to(device), X_i.to(device), features.to(device), y.to(device)

            optimizer.zero_grad()
            outputs = model(X_v, X_i, features)
            loss = criterion(outputs, y)
            loss.backward()
            optimizer.step()
            
            running_loss += loss.item()

            # Calculate accuracy
            _, predicted = torch.max(outputs, 1)
            correct_train += (predicted == y).sum().item()
            total_train += y.size(0)

        train_loss = running_loss / len(dataloader_train)
        train_accuracy = correct_train / total_train

        # Validation step
        model.eval()
        val_loss = 0.0
        correct_val = 0
        total_val = 0
        with torch.no_grad():
            for X_v, X_i, features, y in dataloader_val:
                # Move data to the GPU
                X_v, X_i, features, y = X_v.to(device), X_i.to(device), features.to(device), y.to(device)

                outputs = model(X_v, X_i, features)
                loss = criterion(outputs, y)
                val_loss += loss.item()

                _, predicted = torch.max(outputs, 1)
                correct_val += (predicted == y).sum().item()
                total_val += y.size(0)

        val_loss /= len(dataloader_val)
        val_accuracy = correct_val / total_val

        results["train_loss"].append(train_loss)
        results["train_accuracy"].append(train_accuracy)
        results["val_loss"].append(val_loss)
        results["val_accuracy"].append(val_accuracy)

        print(f"Epoch [{epoch + 1}/{epochs}] - Train Loss: {train_loss:.4f}, Train Accuracy: {train_accuracy:.4f}, "
              f"Val Loss: {val_loss:.4f}, Val Accuracy: {val_accuracy:.4f}")

    return results


# Evaluate the model
def evaluate_model(model, dataloader_test, criterion):
    model.eval()
    all_preds = []
    all_true = []
    total_loss = 0.0
    with torch.no_grad():
        for X_v, X_i, features, y in dataloader_test:
            # Move data to the GPU
            X_v, X_i, features, y = X_v.to(device), X_i.to(device), features.to(device), y.to(device)

            outputs = model(X_v, X_i, features)
            loss = criterion(outputs, y)
            total_loss += loss.item()

            _, preds = torch.max(outputs, 1)
            all_preds.append(preds.cpu().numpy())
            all_true.append(y.cpu().numpy())
    
    all_preds = np.concatenate(all_preds)
    all_true = np.concatenate(all_true)
    accuracy = accuracy_score(all_true, all_preds)
    precision = precision_score(all_true, all_preds, average='weighted')
    f1 = f1_score(all_true, all_preds, average='weighted')
    recall = recall_score(all_true, all_preds, average='weighted')
    cm = confusion_matrix(all_true, all_preds)

    avg_loss = total_loss / len(dataloader_test)

    return accuracy, precision, f1, recall, cm, avg_loss

# Main loop with cross-validation
for bundle, columns in bundle_column_mapping.items():
    print(f"\nProcessing bundle: {bundle}, Columns: {columns}")

    # Load data (vision, imu, rf features, and labels)
    extracted_features, labels, subjects_extracted = extract_features_and_labels(all_data, columns, window_size=60, overlap=45)
    x_v, target, y, x_i, subjects = DataToImage(WindowSize, Overlapping, columns, bundle)


    #apply noise
    #noise_extracted_features=rf_noise_dist(extracted_features)
    #noise_x_v=v_noise_dist(x_v)
    #noise_x_i=i_noise_dist(x_i)
    
    #extracted_features=noise_extracted_features
    #x_v=noise_x_v
    #x_i=noise_x_i
    # Reshape subjects to be a 1D array (9744,)
    subjects = subjects.ravel()

    # Convert data to torch tensors
    x_v = torch.tensor(x_v, dtype=torch.float32)
    x_i = torch.tensor(x_i, dtype=torch.float32)
    y = torch.tensor(np.argmax(y, axis=1), dtype=torch.long)
    extracted_features = torch.tensor(extracted_features, dtype=torch.float32)

    # Add the channel dimension to the input tensors
    x_v = x_v.unsqueeze(1)
    x_i = x_i.unsqueeze(1)

    # Lists to store fold-wise test metrics
    all_test_accuracy = []
    all_test_precisions = []
    all_test_f1_scores = []
    all_test_recalls = []
    all_test_loss = []

    # KFold cross-validation
    unique_subjects = np.unique(subjects)

    for test_subject in unique_subjects:
        # Create train and test masks
        test_mask = subjects == test_subject
        train_mask = subjects != test_subject

        # Split the data based on the masks
        trainx_v, testX_v = x_v[train_mask], x_v[test_mask]
        trainx_i, testX_i = x_i[train_mask], x_i[test_mask]
        trainy, testY = y[train_mask], y[test_mask]
        train_subjects, test_subjects = subjects[train_mask], subjects[test_mask]
        tfeature, test_feature = extracted_features[train_mask], extracted_features[test_mask]
        
        kf = KFold(n_splits=5, shuffle=True, random_state=42)
        for fold, (train_index, val_index) in enumerate(kf.split(trainx_v)):
            X_train_v, X_val_v = trainx_v[train_index], trainx_v[val_index]
            X_train_i, X_val_i = trainx_i[train_index], trainx_i[val_index]
            y_train, y_val = trainy[train_index], trainy[val_index]
            train_features, val_features = tfeature[train_index], tfeature[val_index]

            # Create PyTorch DataLoader for training and validation
            train_data = TensorDataset(X_train_v, X_train_i, train_features, y_train)
            val_data = TensorDataset(X_val_v, X_val_i, val_features, y_val)

            train_loader = DataLoader(train_data, batch_size=16, shuffle=True)
            val_loader = DataLoader(val_data, batch_size=16, shuffle=False)

            # Define model, optimizer, and loss function
            input_shape_v = (1,x_v.shape[2], x_v.shape[3])
            input_shape_i = (1,x_i.shape[2], x_i.shape[3])
            num_classes = len(np.unique(y.numpy()))

            # Move the model to GPU
            model = CNNWithRF(input_shape_v, input_shape_i, num_classes, num_rf_features=train_features.shape[1])
            model.to(device)  # Move the model to GPU

            # Use GPU for optimization and loss calculation
            optimizer = optim.Adam(model.parameters(), lr=0.00031479)
            criterion = nn.CrossEntropyLoss().to(device)  # Move the loss function to GPU

            # Train the model and save metrics
            train_model(model, optimizer, criterion, train_loader, val_loader, epochs=30, fold=fold, bundle=bundle)

            # Evaluate the model on the validation set
            accuracy, precision, f1, recall, cm, loss = evaluate_model(model, val_loader, criterion)

            print(f"Fold {fold} - Accuracy:{accuracy} , Precision: {precision}, F1: {f1}, Recall: {recall}, Loss: {loss}")
            print(f"Confusion Matrix:\n{cm}")

            # Save model, confusion matrix, and metrics
            torch.save(model.state_dict(), f'save/model/{name}_{bundle}_fold_{fold}_{test_subject}.pt')

            sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
            plt.title(f"Confusion Matrix - Fold {fold}")
            plt.savefig(f'save/confusion_matrices/{name}_{bundle}_fold_{fold}_{test_subject}.png')
            plt.close()

                        # Now evaluate on the test set
            test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),
                                     batch_size=1, shuffle=False)
            accuracy_test, precision_test, f1_test, recall_test, cm_test , test_loss = evaluate_model(model, test_loader, criterion)
            print(f"bundle: {bundle}\n")
            print(f"Test Set Evaluation - Fold {fold}")
            print(f"Test Accuracy: {accuracy_test} , Precision: {precision_test}, F1: {f1_test}, Test Recall: {recall_test}, error: {test_loss}")
            print(f"Test Confusion Matrix:\n{cm_test}")
            
            # Save the test metrics for later averaging
            all_test_loss.append(test_loss)
            all_test_accuracy.append(accuracy_test)
            all_test_precisions.append(precision_test)
            all_test_f1_scores.append(f1_test)
            all_test_recalls.append(recall_test)
            all_test_recalls.append(recall_test)
            all_test_loss.append(test_loss)
            # Save the test results in a separate text file
            test_results_filename = f'save/test_results/{name}_{bundle}_test_fold_{fold}_{test_subject}.txt'
            os.makedirs(os.path.dirname(test_results_filename), exist_ok=True)
            with open(test_results_filename, 'w') as f:
                #f.write(f"Test Loss: {loss_test}\n")
                f.write(f"Test Accuracy: {accuracy_test}\n")
                f.write(f"Test Precision: {precision_test}\n")
                f.write(f"Test F1 Score: {f1_test}\n")
                f.write(f"Test Recall: {recall_test}\n")
                f.write(f"Test Recall: {all_test_loss}\n")
                f.write(f"Test Confusion Matrix:\n{cm_test}\n")

            # Save the test confusion matrix
            sns.heatmap(cm_test, annot=True, fmt="d", cmap="Blues")
            plt.title(f"Confusion Matrix - Test Set - Fold {fold}")
            plt.savefig(f'save/confusion_matrices/{name}_{bundle}_test_fold_{fold}_{test_subject}.png')
            plt.close()
    # Calculate mean of test metrics across all folds
    mean_accuracy = np.mean(all_test_accuracy)
    mean_precision = np.mean(all_test_precisions)
    mean_f1_score = np.mean(all_test_f1_scores)
    mean_recall = np.mean(all_test_recalls)
    mean_loss = np.mean(all_test_loss)
    # Save the mean test results to a file
    mean_test_results_filename = f'save/test_results/{name}_{bundle}_mean_test_results.txt'
    with open(mean_test_results_filename, 'w') as f:
        f.write(f"Mean Test Acccuracy: {mean_accuracy}\n")
        f.write(f"Mean Test Precision: {mean_precision}\n")
        f.write(f"Mean Test F1 Score: {mean_f1_score}\n")
        f.write(f"Mean Test Recall: {mean_recall}\n")
        f.write(f"Mean Test Loss: {mean_loss}\n")


Processing bundle: F0, Columns: ['d1', 'd3', 'd5', 'd7', 'd2', 'd4', 'd6', 'd8', 'Raw-accel-x', 'Raw-accel-y', 'Raw-accel-z']
(9744, 1)
(9744, 13, 60)
Epoch [1/30] - Train Loss: 0.7320, Train Accuracy: 0.9302, Val Loss: 0.0637, Val Accuracy: 0.9785
Epoch [2/30] - Train Loss: 0.0532, Train Accuracy: 0.9849, Val Loss: 0.0391, Val Accuracy: 0.9857
Epoch [3/30] - Train Loss: 0.0375, Train Accuracy: 0.9902, Val Loss: 0.0237, Val Accuracy: 0.9922
Epoch [4/30] - Train Loss: 0.0161, Train Accuracy: 0.9953, Val Loss: 0.0353, Val Accuracy: 0.9883
Epoch [5/30] - Train Loss: 0.0182, Train Accuracy: 0.9933, Val Loss: 0.0660, Val Accuracy: 0.9805
Epoch [6/30] - Train Loss: 0.0360, Train Accuracy: 0.9888, Val Loss: 0.0393, Val Accuracy: 0.9870
Epoch [7/30] - Train Loss: 0.0105, Train Accuracy: 0.9966, Val Loss: 0.0512, Val Accuracy: 0.9844
Epoch [8/30] - Train Loss: 0.0134, Train Accuracy: 0.9951, Val Loss: 0.0686, Val Accuracy: 0.9792
Epoch [9/30] - Train Loss: 0.0259, Train Accuracy: 0.9915, Val L

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 0
Test Accuracy: 0.9854085603112841 , Precision: 0.9855064632870929, F1: 0.9853854240589787, Test Recall: 0.9854085603112841, error: 0.08522740250795426
Test Confusion Matrix:
[[467   0   0   0]
 [  0 482  14   3]
 [  0   0 511   0]
 [  1  12   0 566]]
Epoch [1/30] - Train Loss: 1.2525, Train Accuracy: 0.9031, Val Loss: 0.0839, Val Accuracy: 0.9766
Epoch [2/30] - Train Loss: 0.0595, Train Accuracy: 0.9829, Val Loss: 0.0464, Val Accuracy: 0.9870
Epoch [3/30] - Train Loss: 0.0383, Train Accuracy: 0.9891, Val Loss: 0.0398, Val Accuracy: 0.9902
Epoch [4/30] - Train Loss: 0.0293, Train Accuracy: 0.9914, Val Loss: 0.0489, Val Accuracy: 0.9818
Epoch [5/30] - Train Loss: 0.0180, Train Accuracy: 0.9951, Val Loss: 0.0488, Val Accuracy: 0.9863
Epoch [6/30] - Train Loss: 0.0175, Train Accuracy: 0.9950, Val Loss: 0.0675, Val Accuracy: 0.9876
Epoch [7/30] - Train Loss: 0.0054, Train Accuracy: 0.9984, Val Loss: 0.0307, Val Accuracy: 0.9922
Epoch [8/30] - Train L

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 1
Test Accuracy: 0.9883268482490273 , Precision: 0.9883949173934318, F1: 0.9883233216696509, Test Recall: 0.9883268482490273, error: 0.047071101942093525
Test Confusion Matrix:
[[460   0   3   4]
 [  0 492   5   2]
 [  0   0 511   0]
 [  3   4   3 569]]
Epoch [1/30] - Train Loss: 0.6518, Train Accuracy: 0.9148, Val Loss: 0.0672, Val Accuracy: 0.9811
Epoch [2/30] - Train Loss: 0.0439, Train Accuracy: 0.9873, Val Loss: 0.0725, Val Accuracy: 0.9831
Epoch [3/30] - Train Loss: 0.0212, Train Accuracy: 0.9935, Val Loss: 0.0439, Val Accuracy: 0.9863
Epoch [4/30] - Train Loss: 0.0195, Train Accuracy: 0.9937, Val Loss: 0.0549, Val Accuracy: 0.9850
Epoch [5/30] - Train Loss: 0.0220, Train Accuracy: 0.9935, Val Loss: 0.0576, Val Accuracy: 0.9857
Epoch [6/30] - Train Loss: 0.0039, Train Accuracy: 0.9990, Val Loss: 0.0570, Val Accuracy: 0.9863
Epoch [7/30] - Train Loss: 0.0029, Train Accuracy: 0.9995, Val Loss: 0.0417, Val Accuracy: 0.9883
Epoch [8/30] - Train 

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 2
Test Accuracy: 0.9815175097276264 , Precision: 0.9818131472877988, F1: 0.9814516135543911, Test Recall: 0.9815175097276264, error: 0.07632506006132829
Test Confusion Matrix:
[[460   0   1   6]
 [ 18 472   6   3]
 [  0   0 511   0]
 [  2   2   0 575]]
Epoch [1/30] - Train Loss: 0.9190, Train Accuracy: 0.9142, Val Loss: 0.0705, Val Accuracy: 0.9837
Epoch [2/30] - Train Loss: 0.0620, Train Accuracy: 0.9807, Val Loss: 0.1305, Val Accuracy: 0.9746
Epoch [3/30] - Train Loss: 0.0407, Train Accuracy: 0.9870, Val Loss: 0.0577, Val Accuracy: 0.9824
Epoch [4/30] - Train Loss: 0.0229, Train Accuracy: 0.9920, Val Loss: 0.0427, Val Accuracy: 0.9876
Epoch [5/30] - Train Loss: 0.0056, Train Accuracy: 0.9985, Val Loss: 0.0363, Val Accuracy: 0.9896
Epoch [6/30] - Train Loss: 0.0424, Train Accuracy: 0.9867, Val Loss: 0.0456, Val Accuracy: 0.9857
Epoch [7/30] - Train Loss: 0.0295, Train Accuracy: 0.9891, Val Loss: 0.0799, Val Accuracy: 0.9759
Epoch [8/30] - Train L

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 3
Test Accuracy: 0.9858949416342413 , Precision: 0.985942168354301, F1: 0.9858717066616968, Test Recall: 0.9858949416342413, error: 0.06141390988394231
Test Confusion Matrix:
[[466   0   1   0]
 [  3 485   8   3]
 [  0   0 511   0]
 [  1  13   0 565]]
Epoch [1/30] - Train Loss: 0.8743, Train Accuracy: 0.9255, Val Loss: 0.1116, Val Accuracy: 0.9675
Epoch [2/30] - Train Loss: 0.0662, Train Accuracy: 0.9820, Val Loss: 0.1003, Val Accuracy: 0.9727
Epoch [3/30] - Train Loss: 0.0436, Train Accuracy: 0.9862, Val Loss: 0.1039, Val Accuracy: 0.9746
Epoch [4/30] - Train Loss: 0.0253, Train Accuracy: 0.9928, Val Loss: 0.0829, Val Accuracy: 0.9772
Epoch [5/30] - Train Loss: 0.0307, Train Accuracy: 0.9898, Val Loss: 0.1208, Val Accuracy: 0.9551
Epoch [6/30] - Train Loss: 0.0417, Train Accuracy: 0.9872, Val Loss: 0.1407, Val Accuracy: 0.9577
Epoch [7/30] - Train Loss: 0.0420, Train Accuracy: 0.9875, Val Loss: 0.1089, Val Accuracy: 0.9759
Epoch [8/30] - Train Lo

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 4
Test Accuracy: 0.9824902723735408 , Precision: 0.9826886583661817, F1: 0.9824630392267544, Test Recall: 0.9824902723735408, error: 0.11710647209798253
Test Confusion Matrix:
[[466   0   1   0]
 [  4 486   7   2]
 [  0   0 511   0]
 [  0  18   4 557]]
Epoch [1/30] - Train Loss: 0.9382, Train Accuracy: 0.9328, Val Loss: 0.0423, Val Accuracy: 0.9911
Epoch [2/30] - Train Loss: 0.0299, Train Accuracy: 0.9917, Val Loss: 0.0293, Val Accuracy: 0.9917
Epoch [3/30] - Train Loss: 0.0154, Train Accuracy: 0.9965, Val Loss: 0.0123, Val Accuracy: 0.9968
Epoch [4/30] - Train Loss: 0.0118, Train Accuracy: 0.9967, Val Loss: 0.0190, Val Accuracy: 0.9962
Epoch [5/30] - Train Loss: 0.0167, Train Accuracy: 0.9947, Val Loss: 0.0273, Val Accuracy: 0.9911
Epoch [6/30] - Train Loss: 0.0199, Train Accuracy: 0.9935, Val Loss: 0.0940, Val Accuracy: 0.9676
Epoch [7/30] - Train Loss: 0.0132, Train Accuracy: 0.9959, Val Loss: 0.0183, Val Accuracy: 0.9955
Epoch [8/30] - Train L

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 0
Test Accuracy: 0.9353813559322034 , Precision: 0.9456087219821095, F1: 0.9357714169583979, Test Recall: 0.9353813559322034, error: 0.8882241690829086
Test Confusion Matrix:
[[554  86  13  10]
 [  0 356   3   0]
 [  1   8 445   1]
 [  0   0   0 411]]
Epoch [1/30] - Train Loss: 0.6930, Train Accuracy: 0.9227, Val Loss: 0.0514, Val Accuracy: 0.9847
Epoch [2/30] - Train Loss: 0.0295, Train Accuracy: 0.9933, Val Loss: 0.0320, Val Accuracy: 0.9898
Epoch [3/30] - Train Loss: 0.0243, Train Accuracy: 0.9928, Val Loss: 0.0239, Val Accuracy: 0.9917
Epoch [4/30] - Train Loss: 0.0149, Train Accuracy: 0.9954, Val Loss: 0.0234, Val Accuracy: 0.9917
Epoch [5/30] - Train Loss: 0.0039, Train Accuracy: 0.9994, Val Loss: 0.0164, Val Accuracy: 0.9924
Epoch [6/30] - Train Loss: 0.0049, Train Accuracy: 0.9987, Val Loss: 0.0249, Val Accuracy: 0.9905
Epoch [7/30] - Train Loss: 0.0177, Train Accuracy: 0.9946, Val Loss: 0.0354, Val Accuracy: 0.9917
Epoch [8/30] - Train Lo

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 1
Test Accuracy: 0.9507415254237288 , Precision: 0.9571135662987377, F1: 0.9510257428935189, Test Recall: 0.9507415254237288, error: 0.8768628920406042
Test Confusion Matrix:
[[577  72  10   4]
 [  0 353   6   0]
 [  0   1 454   0]
 [  0   0   0 411]]
Epoch [1/30] - Train Loss: 0.6471, Train Accuracy: 0.9335, Val Loss: 0.0566, Val Accuracy: 0.9815
Epoch [2/30] - Train Loss: 0.0261, Train Accuracy: 0.9941, Val Loss: 0.0259, Val Accuracy: 0.9917
Epoch [3/30] - Train Loss: 0.0150, Train Accuracy: 0.9962, Val Loss: 0.0185, Val Accuracy: 0.9943
Epoch [4/30] - Train Loss: 0.0122, Train Accuracy: 0.9965, Val Loss: 0.0201, Val Accuracy: 0.9917
Epoch [5/30] - Train Loss: 0.0071, Train Accuracy: 0.9981, Val Loss: 0.0124, Val Accuracy: 0.9962
Epoch [6/30] - Train Loss: 0.0050, Train Accuracy: 0.9984, Val Loss: 0.0226, Val Accuracy: 0.9949
Epoch [7/30] - Train Loss: 0.0271, Train Accuracy: 0.9924, Val Loss: 0.0198, Val Accuracy: 0.9936
Epoch [8/30] - Train Lo

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 2
Test Accuracy: 0.9470338983050848 , Precision: 0.9565794810596958, F1: 0.9480052830698369, Test Recall: 0.9470338983050848, error: 0.8317901052424479
Test Confusion Matrix:
[[575  79   5   4]
 [  0 359   0   0]
 [  0  11 443   1]
 [  0   0   0 411]]
Epoch [1/30] - Train Loss: 0.7705, Train Accuracy: 0.9402, Val Loss: 0.0268, Val Accuracy: 0.9936
Epoch [2/30] - Train Loss: 0.0253, Train Accuracy: 0.9927, Val Loss: 0.0236, Val Accuracy: 0.9936
Epoch [3/30] - Train Loss: 0.0082, Train Accuracy: 0.9981, Val Loss: 0.0107, Val Accuracy: 0.9962
Epoch [4/30] - Train Loss: 0.0013, Train Accuracy: 1.0000, Val Loss: 0.0061, Val Accuracy: 0.9981
Epoch [5/30] - Train Loss: 0.0005, Train Accuracy: 1.0000, Val Loss: 0.0066, Val Accuracy: 0.9987
Epoch [6/30] - Train Loss: 0.0002, Train Accuracy: 1.0000, Val Loss: 0.0058, Val Accuracy: 0.9987
Epoch [7/30] - Train Loss: 0.0002, Train Accuracy: 1.0000, Val Loss: 0.0045, Val Accuracy: 0.9987
Epoch [8/30] - Train Lo

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 3
Test Accuracy: 0.9433262711864406 , Precision: 0.9534177154070348, F1: 0.9445013837633083, Test Recall: 0.9433262711864406, error: 0.7965552949237623
Test Confusion Matrix:
[[575  77   8   3]
 [  0 357   1   1]
 [  0  17 438   0]
 [  0   0   0 411]]
Epoch [1/30] - Train Loss: 0.7971, Train Accuracy: 0.9212, Val Loss: 0.1021, Val Accuracy: 0.9784
Epoch [2/30] - Train Loss: 0.0256, Train Accuracy: 0.9933, Val Loss: 0.0350, Val Accuracy: 0.9943
Epoch [3/30] - Train Loss: 0.0094, Train Accuracy: 0.9979, Val Loss: 0.0341, Val Accuracy: 0.9905
Epoch [4/30] - Train Loss: 0.0043, Train Accuracy: 0.9994, Val Loss: 0.0185, Val Accuracy: 0.9943
Epoch [5/30] - Train Loss: 0.0084, Train Accuracy: 0.9978, Val Loss: 0.0298, Val Accuracy: 0.9936
Epoch [6/30] - Train Loss: 0.0034, Train Accuracy: 0.9992, Val Loss: 0.0210, Val Accuracy: 0.9936
Epoch [7/30] - Train Loss: 0.0004, Train Accuracy: 1.0000, Val Loss: 0.0145, Val Accuracy: 0.9955
Epoch [8/30] - Train Lo

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 4
Test Accuracy: 0.9454449152542372 , Precision: 0.9534576941273385, F1: 0.945839006650687, Test Recall: 0.9454449152542372, error: 0.6865862614229504
Test Confusion Matrix:
[[568  80   7   8]
 [  0 355   3   1]
 [  1   3 451   0]
 [  0   0   0 411]]
Epoch [1/30] - Train Loss: 0.9251, Train Accuracy: 0.9223, Val Loss: 0.1073, Val Accuracy: 0.9715
Epoch [2/30] - Train Loss: 0.0565, Train Accuracy: 0.9829, Val Loss: 0.1043, Val Accuracy: 0.9561
Epoch [3/30] - Train Loss: 0.0297, Train Accuracy: 0.9904, Val Loss: 0.0196, Val Accuracy: 0.9953
Epoch [4/30] - Train Loss: 0.0221, Train Accuracy: 0.9935, Val Loss: 0.0224, Val Accuracy: 0.9941
Epoch [5/30] - Train Loss: 0.0271, Train Accuracy: 0.9907, Val Loss: 0.0296, Val Accuracy: 0.9899
Epoch [6/30] - Train Loss: 0.0303, Train Accuracy: 0.9901, Val Loss: 0.0301, Val Accuracy: 0.9881
Epoch [7/30] - Train Loss: 0.0352, Train Accuracy: 0.9887, Val Loss: 0.0196, Val Accuracy: 0.9953
Epoch [8/30] - Train Los

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 0
Test Accuracy: 0.9650455927051672 , Precision: 0.9690460130344308, F1: 0.965302559984418, Test Recall: 0.9650455927051672, error: 0.15037727318230248
Test Confusion Matrix:
[[285   1   0   1]
 [ 39 312   0   0]
 [  4   0 310   1]
 [  0   0   0 363]]
Epoch [1/30] - Train Loss: 1.0330, Train Accuracy: 0.9202, Val Loss: 0.0906, Val Accuracy: 0.9745
Epoch [2/30] - Train Loss: 0.0482, Train Accuracy: 0.9859, Val Loss: 0.0748, Val Accuracy: 0.9781
Epoch [3/30] - Train Loss: 0.0204, Train Accuracy: 0.9941, Val Loss: 0.1101, Val Accuracy: 0.9686
Epoch [4/30] - Train Loss: 0.0191, Train Accuracy: 0.9948, Val Loss: 0.0353, Val Accuracy: 0.9887
Epoch [5/30] - Train Loss: 0.0023, Train Accuracy: 0.9999, Val Loss: 0.0309, Val Accuracy: 0.9899
Epoch [6/30] - Train Loss: 0.0011, Train Accuracy: 1.0000, Val Loss: 0.0364, Val Accuracy: 0.9905
Epoch [7/30] - Train Loss: 0.0004, Train Accuracy: 1.0000, Val Loss: 0.0248, Val Accuracy: 0.9929
Epoch [8/30] - Train Lo

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 1
Test Accuracy: 0.9802431610942249 , Precision: 0.9815425103892291, F1: 0.9804192069438, Test Recall: 0.9802431610942249, error: 0.0728500649588534
Test Confusion Matrix:
[[286   1   0   0]
 [ 15 335   1   0]
 [  9   0 306   0]
 [  0   0   0 363]]
Epoch [1/30] - Train Loss: 0.6056, Train Accuracy: 0.9264, Val Loss: 0.0548, Val Accuracy: 0.9816
Epoch [2/30] - Train Loss: 0.0481, Train Accuracy: 0.9858, Val Loss: 0.0449, Val Accuracy: 0.9870
Epoch [3/30] - Train Loss: 0.0262, Train Accuracy: 0.9930, Val Loss: 0.0489, Val Accuracy: 0.9875
Epoch [4/30] - Train Loss: 0.0287, Train Accuracy: 0.9907, Val Loss: 0.0291, Val Accuracy: 0.9929
Epoch [5/30] - Train Loss: 0.0243, Train Accuracy: 0.9926, Val Loss: 0.0642, Val Accuracy: 0.9792
Epoch [6/30] - Train Loss: 0.0279, Train Accuracy: 0.9915, Val Loss: 0.0315, Val Accuracy: 0.9905
Epoch [7/30] - Train Loss: 0.0190, Train Accuracy: 0.9950, Val Loss: 0.0332, Val Accuracy: 0.9887
Epoch [8/30] - Train Loss:

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 2
Test Accuracy: 0.9741641337386018 , Precision: 0.9764736702669469, F1: 0.9743276039632935, Test Recall: 0.9741641337386018, error: 0.10909928901423155
Test Confusion Matrix:
[[285   0   0   2]
 [ 29 322   0   0]
 [  3   0 312   0]
 [  0   0   0 363]]
Epoch [1/30] - Train Loss: 0.8352, Train Accuracy: 0.9275, Val Loss: 0.1107, Val Accuracy: 0.9745
Epoch [2/30] - Train Loss: 0.0652, Train Accuracy: 0.9807, Val Loss: 0.0757, Val Accuracy: 0.9864
Epoch [3/30] - Train Loss: 0.0476, Train Accuracy: 0.9858, Val Loss: 0.0517, Val Accuracy: 0.9887
Epoch [4/30] - Train Loss: 0.0321, Train Accuracy: 0.9905, Val Loss: 0.0561, Val Accuracy: 0.9840
Epoch [5/30] - Train Loss: 0.0247, Train Accuracy: 0.9929, Val Loss: 0.0482, Val Accuracy: 0.9875
Epoch [6/30] - Train Loss: 0.0280, Train Accuracy: 0.9917, Val Loss: 0.0822, Val Accuracy: 0.9739
Epoch [7/30] - Train Loss: 0.0293, Train Accuracy: 0.9908, Val Loss: 0.0964, Val Accuracy: 0.9804
Epoch [8/30] - Train L

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 3
Test Accuracy: 0.9855623100303952 , Precision: 0.9858018747149094, F1: 0.9855939664239327, Test Recall: 0.9855623100303952, error: 0.052675980198225586
Test Confusion Matrix:
[[283   2   1   1]
 [ 10 340   1   0]
 [  3   1 311   0]
 [  0   0   0 363]]
Epoch [1/30] - Train Loss: 1.0054, Train Accuracy: 0.9281, Val Loss: 0.0816, Val Accuracy: 0.9763
Epoch [2/30] - Train Loss: 0.0528, Train Accuracy: 0.9856, Val Loss: 0.0908, Val Accuracy: 0.9745
Epoch [3/30] - Train Loss: 0.0398, Train Accuracy: 0.9862, Val Loss: 0.0342, Val Accuracy: 0.9864
Epoch [4/30] - Train Loss: 0.0174, Train Accuracy: 0.9950, Val Loss: 0.0533, Val Accuracy: 0.9852
Epoch [5/30] - Train Loss: 0.0153, Train Accuracy: 0.9957, Val Loss: 0.0655, Val Accuracy: 0.9840
Epoch [6/30] - Train Loss: 0.0120, Train Accuracy: 0.9961, Val Loss: 0.0478, Val Accuracy: 0.9875
Epoch [7/30] - Train Loss: 0.0105, Train Accuracy: 0.9964, Val Loss: 0.0447, Val Accuracy: 0.9875
Epoch [8/30] - Train 

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 4
Test Accuracy: 0.973404255319149 , Precision: 0.9747680937623928, F1: 0.9735664104447472, Test Recall: 0.973404255319149, error: 0.10727560540796
Test Confusion Matrix:
[[283   2   1   1]
 [ 21 330   0   0]
 [  6   2 305   2]
 [  0   0   0 363]]
Epoch [1/30] - Train Loss: 0.8336, Train Accuracy: 0.9264, Val Loss: 0.0504, Val Accuracy: 0.9867
Epoch [2/30] - Train Loss: 0.0540, Train Accuracy: 0.9833, Val Loss: 0.0580, Val Accuracy: 0.9843
Epoch [3/30] - Train Loss: 0.0347, Train Accuracy: 0.9881, Val Loss: 0.0523, Val Accuracy: 0.9873
Epoch [4/30] - Train Loss: 0.0248, Train Accuracy: 0.9925, Val Loss: 0.0388, Val Accuracy: 0.9880
Epoch [5/30] - Train Loss: 0.0252, Train Accuracy: 0.9916, Val Loss: 0.0433, Val Accuracy: 0.9873
Epoch [6/30] - Train Loss: 0.0166, Train Accuracy: 0.9938, Val Loss: 0.0536, Val Accuracy: 0.9837
Epoch [7/30] - Train Loss: 0.0266, Train Accuracy: 0.9928, Val Loss: 0.0817, Val Accuracy: 0.9843
Epoch [8/30] - Train Loss: 

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 0
Test Accuracy: 0.9958448753462604 , Precision: 0.9958458846719316, F1: 0.9958404010756557, Test Recall: 0.9958448753462604, error: 0.022430626552017274
Test Confusion Matrix:
[[347   0   0   0]
 [  1 351   2   1]
 [  0   0 323   0]
 [  0   2   0 417]]
Epoch [1/30] - Train Loss: 0.5504, Train Accuracy: 0.9354, Val Loss: 0.0606, Val Accuracy: 0.9825
Epoch [2/30] - Train Loss: 0.0549, Train Accuracy: 0.9843, Val Loss: 0.1398, Val Accuracy: 0.9590
Epoch [3/30] - Train Loss: 0.0287, Train Accuracy: 0.9901, Val Loss: 0.0449, Val Accuracy: 0.9880
Epoch [4/30] - Train Loss: 0.0275, Train Accuracy: 0.9923, Val Loss: 0.0455, Val Accuracy: 0.9861
Epoch [5/30] - Train Loss: 0.0165, Train Accuracy: 0.9953, Val Loss: 0.0603, Val Accuracy: 0.9819
Epoch [6/30] - Train Loss: 0.0240, Train Accuracy: 0.9916, Val Loss: 0.1265, Val Accuracy: 0.9729
Epoch [7/30] - Train Loss: 0.0181, Train Accuracy: 0.9935, Val Loss: 0.0468, Val Accuracy: 0.9886
Epoch [8/30] - Train 

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 1
Test Accuracy: 0.9889196675900277 , Precision: 0.9889433850838415, F1: 0.9888996654582166, Test Recall: 0.9889196675900277, error: 0.04343038840614687
Test Confusion Matrix:
[[346   0   1   0]
 [  3 346   4   2]
 [  0   0 323   0]
 [  1   5   0 413]]
Epoch [1/30] - Train Loss: 1.0814, Train Accuracy: 0.9233, Val Loss: 0.0638, Val Accuracy: 0.9813
Epoch [2/30] - Train Loss: 0.0545, Train Accuracy: 0.9828, Val Loss: 0.0844, Val Accuracy: 0.9795
Epoch [3/30] - Train Loss: 0.0346, Train Accuracy: 0.9883, Val Loss: 0.0378, Val Accuracy: 0.9886
Epoch [4/30] - Train Loss: 0.0203, Train Accuracy: 0.9946, Val Loss: 0.1543, Val Accuracy: 0.9596
Epoch [5/30] - Train Loss: 0.0311, Train Accuracy: 0.9889, Val Loss: 0.0341, Val Accuracy: 0.9898
Epoch [6/30] - Train Loss: 0.0275, Train Accuracy: 0.9911, Val Loss: 0.0620, Val Accuracy: 0.9831
Epoch [7/30] - Train Loss: 0.0120, Train Accuracy: 0.9961, Val Loss: 0.0494, Val Accuracy: 0.9831
Epoch [8/30] - Train L

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 2
Test Accuracy: 0.974376731301939 , Precision: 0.975651607206867, F1: 0.974171672007195, Test Recall: 0.974376731301939, error: 0.15428895587452796
Test Confusion Matrix:
[[347   0   0   0]
 [ 23 322   7   3]
 [  1   0 322   0]
 [  2   1   0 416]]
Epoch [1/30] - Train Loss: 0.9560, Train Accuracy: 0.9142, Val Loss: 0.1365, Val Accuracy: 0.9633
Epoch [2/30] - Train Loss: 0.0592, Train Accuracy: 0.9827, Val Loss: 0.0515, Val Accuracy: 0.9861
Epoch [3/30] - Train Loss: 0.0303, Train Accuracy: 0.9923, Val Loss: 0.1015, Val Accuracy: 0.9777
Epoch [4/30] - Train Loss: 0.0249, Train Accuracy: 0.9922, Val Loss: 0.0486, Val Accuracy: 0.9861
Epoch [5/30] - Train Loss: 0.0130, Train Accuracy: 0.9959, Val Loss: 0.0606, Val Accuracy: 0.9867
Epoch [6/30] - Train Loss: 0.0521, Train Accuracy: 0.9834, Val Loss: 0.0608, Val Accuracy: 0.9789
Epoch [7/30] - Train Loss: 0.0304, Train Accuracy: 0.9898, Val Loss: 0.0514, Val Accuracy: 0.9861
Epoch [8/30] - Train Loss:

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 3
Test Accuracy: 0.9875346260387812 , Precision: 0.9876583009031278, F1: 0.9874904912441527, Test Recall: 0.9875346260387812, error: 0.048124030141825404
Test Confusion Matrix:
[[346   0   1   0]
 [  8 341   0   6]
 [  0   0 323   0]
 [  1   2   0 416]]
Epoch [1/30] - Train Loss: 0.9869, Train Accuracy: 0.9101, Val Loss: 0.0946, Val Accuracy: 0.9711
Epoch [2/30] - Train Loss: 0.0561, Train Accuracy: 0.9828, Val Loss: 0.0858, Val Accuracy: 0.9807
Epoch [3/30] - Train Loss: 0.0276, Train Accuracy: 0.9925, Val Loss: 0.0273, Val Accuracy: 0.9892
Epoch [4/30] - Train Loss: 0.0192, Train Accuracy: 0.9938, Val Loss: 0.0428, Val Accuracy: 0.9837
Epoch [5/30] - Train Loss: 0.0167, Train Accuracy: 0.9946, Val Loss: 0.0424, Val Accuracy: 0.9898
Epoch [6/30] - Train Loss: 0.0249, Train Accuracy: 0.9913, Val Loss: 0.0843, Val Accuracy: 0.9795
Epoch [7/30] - Train Loss: 0.0209, Train Accuracy: 0.9931, Val Loss: 0.0671, Val Accuracy: 0.9813
Epoch [8/30] - Train 

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 4
Test Accuracy: 0.9868421052631579 , Precision: 0.9869955948589119, F1: 0.9867685581733436, Test Recall: 0.9868421052631579, error: 0.0435805726532303
Test Confusion Matrix:
[[346   0   0   1]
 [  7 339   4   5]
 [  1   0 322   0]
 [  0   1   0 418]]
Epoch [1/30] - Train Loss: 1.1183, Train Accuracy: 0.9265, Val Loss: 0.0817, Val Accuracy: 0.9793
Epoch [2/30] - Train Loss: 0.0379, Train Accuracy: 0.9898, Val Loss: 0.0591, Val Accuracy: 0.9786
Epoch [3/30] - Train Loss: 0.0260, Train Accuracy: 0.9930, Val Loss: 0.0464, Val Accuracy: 0.9893
Epoch [4/30] - Train Loss: 0.0208, Train Accuracy: 0.9935, Val Loss: 0.0296, Val Accuracy: 0.9886
Epoch [5/30] - Train Loss: 0.0183, Train Accuracy: 0.9940, Val Loss: 0.0432, Val Accuracy: 0.9900
Epoch [6/30] - Train Loss: 0.0082, Train Accuracy: 0.9977, Val Loss: 0.0254, Val Accuracy: 0.9906
Epoch [7/30] - Train Loss: 0.0113, Train Accuracy: 0.9953, Val Loss: 0.0319, Val Accuracy: 0.9906
Epoch [8/30] - Train Lo

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 0
Test Accuracy: 0.9068541300527241 , Precision: 0.9257655991964359, F1: 0.9093625263053557, Test Recall: 0.9068541300527241, error: 0.3935684805684782
Test Confusion Matrix:
[[398   1   0   0]
 [ 39 517  12   3]
 [  4  24 668   7]
 [120   2   0 481]]
Epoch [1/30] - Train Loss: 0.6818, Train Accuracy: 0.9347, Val Loss: 0.0585, Val Accuracy: 0.9839
Epoch [2/30] - Train Loss: 0.0471, Train Accuracy: 0.9866, Val Loss: 0.0945, Val Accuracy: 0.9699
Epoch [3/30] - Train Loss: 0.0283, Train Accuracy: 0.9901, Val Loss: 0.0241, Val Accuracy: 0.9926
Epoch [4/30] - Train Loss: 0.0171, Train Accuracy: 0.9953, Val Loss: 0.0742, Val Accuracy: 0.9813
Epoch [5/30] - Train Loss: 0.0259, Train Accuracy: 0.9915, Val Loss: 0.0176, Val Accuracy: 0.9960
Epoch [6/30] - Train Loss: 0.0066, Train Accuracy: 0.9977, Val Loss: 0.0164, Val Accuracy: 0.9960
Epoch [7/30] - Train Loss: 0.0010, Train Accuracy: 1.0000, Val Loss: 0.0122, Val Accuracy: 0.9967
Epoch [8/30] - Train Lo

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 1
Test Accuracy: 0.8563268892794376 , Precision: 0.9047472843463861, F1: 0.8595207568946777, Test Recall: 0.8563268892794376, error: 0.8511460715733138
Test Confusion Matrix:
[[396   2   1   0]
 [ 63 481  23   4]
 [  3   2 694   4]
 [213   0  12 378]]
Epoch [1/30] - Train Loss: 0.7682, Train Accuracy: 0.9315, Val Loss: 0.1587, Val Accuracy: 0.9491
Epoch [2/30] - Train Loss: 0.0604, Train Accuracy: 0.9829, Val Loss: 0.0935, Val Accuracy: 0.9752
Epoch [3/30] - Train Loss: 0.0411, Train Accuracy: 0.9883, Val Loss: 0.0651, Val Accuracy: 0.9799
Epoch [4/30] - Train Loss: 0.0315, Train Accuracy: 0.9888, Val Loss: 0.0822, Val Accuracy: 0.9799
Epoch [5/30] - Train Loss: 0.0226, Train Accuracy: 0.9930, Val Loss: 0.0564, Val Accuracy: 0.9866
Epoch [6/30] - Train Loss: 0.0127, Train Accuracy: 0.9967, Val Loss: 0.0689, Val Accuracy: 0.9799
Epoch [7/30] - Train Loss: 0.0109, Train Accuracy: 0.9963, Val Loss: 0.0483, Val Accuracy: 0.9900
Epoch [8/30] - Train Lo

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 2
Test Accuracy: 0.8554481546572935 , Precision: 0.9000305450129802, F1: 0.8603583231783771, Test Recall: 0.8554481546572935, error: 0.8998755888085058
Test Confusion Matrix:
[[394   2   0   3]
 [ 73 487   8   3]
 [  3  18 672  10]
 [201   7   1 394]]
Epoch [1/30] - Train Loss: 1.3038, Train Accuracy: 0.9172, Val Loss: 0.0880, Val Accuracy: 0.9745
Epoch [2/30] - Train Loss: 0.0545, Train Accuracy: 0.9841, Val Loss: 0.1435, Val Accuracy: 0.9457
Epoch [3/30] - Train Loss: 0.0292, Train Accuracy: 0.9913, Val Loss: 0.0450, Val Accuracy: 0.9833
Epoch [4/30] - Train Loss: 0.0286, Train Accuracy: 0.9905, Val Loss: 0.0468, Val Accuracy: 0.9846
Epoch [5/30] - Train Loss: 0.0123, Train Accuracy: 0.9962, Val Loss: 0.0369, Val Accuracy: 0.9886
Epoch [6/30] - Train Loss: 0.0032, Train Accuracy: 0.9995, Val Loss: 0.0286, Val Accuracy: 0.9913
Epoch [7/30] - Train Loss: 0.0011, Train Accuracy: 1.0000, Val Loss: 0.0309, Val Accuracy: 0.9900
Epoch [8/30] - Train Lo

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 3
Test Accuracy: 0.9033391915641477 , Precision: 0.927784201642173, F1: 0.9068780497736363, Test Recall: 0.9033391915641477, error: 0.3665660097383461
Test Confusion Matrix:
[[395   3   0   1]
 [ 54 500  10   7]
 [  6   9 687   1]
 [128   0   1 474]]
Epoch [1/30] - Train Loss: 0.9186, Train Accuracy: 0.9111, Val Loss: 0.0495, Val Accuracy: 0.9906
Epoch [2/30] - Train Loss: 0.0420, Train Accuracy: 0.9886, Val Loss: 0.0304, Val Accuracy: 0.9920
Epoch [3/30] - Train Loss: 0.0191, Train Accuracy: 0.9953, Val Loss: 0.0329, Val Accuracy: 0.9906
Epoch [4/30] - Train Loss: 0.0111, Train Accuracy: 0.9977, Val Loss: 0.0258, Val Accuracy: 0.9940
Epoch [5/30] - Train Loss: 0.0118, Train Accuracy: 0.9962, Val Loss: 0.0256, Val Accuracy: 0.9933
Epoch [6/30] - Train Loss: 0.0026, Train Accuracy: 0.9998, Val Loss: 0.0118, Val Accuracy: 0.9987
Epoch [7/30] - Train Loss: 0.0021, Train Accuracy: 0.9997, Val Loss: 0.0116, Val Accuracy: 0.9960
Epoch [8/30] - Train Los

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 4
Test Accuracy: 0.8708260105448155 , Precision: 0.9119632362671901, F1: 0.8746046367049103, Test Recall: 0.8708260105448155, error: 0.6932455795711643
Test Confusion Matrix:
[[399   0   0   0]
 [ 54 492  21   4]
 [  7   8 685   3]
 [192   3   2 406]]
Epoch [1/30] - Train Loss: 0.9001, Train Accuracy: 0.9291, Val Loss: 0.0666, Val Accuracy: 0.9827
Epoch [2/30] - Train Loss: 0.0519, Train Accuracy: 0.9830, Val Loss: 0.0637, Val Accuracy: 0.9772
Epoch [3/30] - Train Loss: 0.0366, Train Accuracy: 0.9896, Val Loss: 0.0331, Val Accuracy: 0.9878
Epoch [4/30] - Train Loss: 0.0198, Train Accuracy: 0.9935, Val Loss: 0.1127, Val Accuracy: 0.9638
Epoch [5/30] - Train Loss: 0.0123, Train Accuracy: 0.9974, Val Loss: 0.0951, Val Accuracy: 0.9794
Epoch [6/30] - Train Loss: 0.0184, Train Accuracy: 0.9935, Val Loss: 0.0393, Val Accuracy: 0.9844
Epoch [7/30] - Train Loss: 0.0183, Train Accuracy: 0.9935, Val Loss: 0.0305, Val Accuracy: 0.9894
Epoch [8/30] - Train Lo

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 0
Test Accuracy: 0.9973821989528796 , Precision: 0.9974054682955207, F1: 0.9973801573158754, Test Recall: 0.9973821989528796, error: 0.010425933862710443
Test Confusion Matrix:
[[165   0   2   0]
 [  0 191   0   0]
 [  0   0 223   0]
 [  0   0   0 183]]
Epoch [1/30] - Train Loss: 0.9952, Train Accuracy: 0.9290, Val Loss: 0.0805, Val Accuracy: 0.9755
Epoch [2/30] - Train Loss: 0.0535, Train Accuracy: 0.9848, Val Loss: 0.0419, Val Accuracy: 0.9889
Epoch [3/30] - Train Loss: 0.0270, Train Accuracy: 0.9925, Val Loss: 0.0764, Val Accuracy: 0.9777
Epoch [4/30] - Train Loss: 0.0190, Train Accuracy: 0.9922, Val Loss: 0.0280, Val Accuracy: 0.9905
Epoch [5/30] - Train Loss: 0.0199, Train Accuracy: 0.9933, Val Loss: 0.0441, Val Accuracy: 0.9889
Epoch [6/30] - Train Loss: 0.0134, Train Accuracy: 0.9955, Val Loss: 0.0295, Val Accuracy: 0.9916
Epoch [7/30] - Train Loss: 0.0197, Train Accuracy: 0.9930, Val Loss: 0.0798, Val Accuracy: 0.9833
Epoch [8/30] - Train 

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 1
Test Accuracy: 0.9960732984293194 , Precision: 0.9961254227864523, F1: 0.9960809405382746, Test Recall: 0.9960732984293194, error: 0.021630365759245516
Test Confusion Matrix:
[[166   0   1   0]
 [  0 190   1   0]
 [  0   0 223   0]
 [  0   0   1 182]]
Epoch [1/30] - Train Loss: 0.9513, Train Accuracy: 0.9179, Val Loss: 0.0595, Val Accuracy: 0.9816
Epoch [2/30] - Train Loss: 0.0469, Train Accuracy: 0.9855, Val Loss: 0.0717, Val Accuracy: 0.9827
Epoch [3/30] - Train Loss: 0.0337, Train Accuracy: 0.9890, Val Loss: 0.0456, Val Accuracy: 0.9855
Epoch [4/30] - Train Loss: 0.0184, Train Accuracy: 0.9947, Val Loss: 0.0538, Val Accuracy: 0.9866
Epoch [5/30] - Train Loss: 0.0249, Train Accuracy: 0.9921, Val Loss: 0.0682, Val Accuracy: 0.9861
Epoch [6/30] - Train Loss: 0.0167, Train Accuracy: 0.9948, Val Loss: 0.1141, Val Accuracy: 0.9705
Epoch [7/30] - Train Loss: 0.0280, Train Accuracy: 0.9915, Val Loss: 0.0330, Val Accuracy: 0.9911
Epoch [8/30] - Train 

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 2
Test Accuracy: 0.9947643979057592 , Precision: 0.9948566552113846, F1: 0.9947762715738488, Test Recall: 0.9947643979057592, error: 0.034443009101184
Test Confusion Matrix:
[[165   0   2   0]
 [  0 190   1   0]
 [  0   0 223   0]
 [  0   0   1 182]]
Epoch [1/30] - Train Loss: 0.7405, Train Accuracy: 0.9240, Val Loss: 0.0928, Val Accuracy: 0.9772
Epoch [2/30] - Train Loss: 0.0603, Train Accuracy: 0.9818, Val Loss: 0.1460, Val Accuracy: 0.9532
Epoch [3/30] - Train Loss: 0.0396, Train Accuracy: 0.9868, Val Loss: 0.0621, Val Accuracy: 0.9833
Epoch [4/30] - Train Loss: 0.0287, Train Accuracy: 0.9910, Val Loss: 0.0483, Val Accuracy: 0.9866
Epoch [5/30] - Train Loss: 0.0298, Train Accuracy: 0.9907, Val Loss: 0.0311, Val Accuracy: 0.9928
Epoch [6/30] - Train Loss: 0.0138, Train Accuracy: 0.9955, Val Loss: 0.0393, Val Accuracy: 0.9905
Epoch [7/30] - Train Loss: 0.0267, Train Accuracy: 0.9912, Val Loss: 0.0477, Val Accuracy: 0.9844
Epoch [8/30] - Train Los

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 3
Test Accuracy: 0.9973821989528796 , Precision: 0.9974054682955207, F1: 0.9973845315271501, Test Recall: 0.9973821989528796, error: 0.025730628153149894
Test Confusion Matrix:
[[167   0   0   0]
 [  0 190   1   0]
 [  0   0 223   0]
 [  0   0   1 182]]
Epoch [1/30] - Train Loss: 0.7167, Train Accuracy: 0.9305, Val Loss: 0.0855, Val Accuracy: 0.9794
Epoch [2/30] - Train Loss: 0.0549, Train Accuracy: 0.9832, Val Loss: 0.0689, Val Accuracy: 0.9833
Epoch [3/30] - Train Loss: 0.0376, Train Accuracy: 0.9891, Val Loss: 0.0588, Val Accuracy: 0.9850
Epoch [4/30] - Train Loss: 0.0215, Train Accuracy: 0.9933, Val Loss: 0.0727, Val Accuracy: 0.9749
Epoch [5/30] - Train Loss: 0.0206, Train Accuracy: 0.9939, Val Loss: 0.0711, Val Accuracy: 0.9783
Epoch [6/30] - Train Loss: 0.0300, Train Accuracy: 0.9901, Val Loss: 0.0765, Val Accuracy: 0.9822
Epoch [7/30] - Train Loss: 0.0144, Train Accuracy: 0.9948, Val Loss: 0.0806, Val Accuracy: 0.9788
Epoch [8/30] - Train 

/tmp/ipykernel_25415/3627583972.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_loader = DataLoader(TensorDataset(torch.tensor(testX_v), torch.tensor(testX_i), torch.tensor(test_feature), torch.tensor(testY)),


bundle: F0

Test Set Evaluation - Fold 4
Test Accuracy: 0.9921465968586387 , Precision: 0.9922619184906706, F1: 0.992149769950817, Test Recall: 0.9921465968586387, error: 0.035693616964899914
Test Confusion Matrix:
[[163   0   4   0]
 [  0 190   1   0]
 [  0   1 222   0]
 [  0   0   0 183]]
